name: Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:

  complete:
    if: always()
    needs: [fmt, build-and-test, doc]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - run: make fmt

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - run: cargo install --locked --version 0.9.33 cargo-nextest
    - run: make check
    - run: make test

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup install nightly
    - run: make doc
